@ECHO OFF
rem region_finder tiles f:/cut
rem region_finder tiles 11
rem region_finder tiles 10
rem region_finder tiles 9
rem region_finder tiles 8
rem region_finder tiles 7
rem region_finder tiles 6
rem region_finder tiles 5
rem region_finder tiles 4
rem region_finder tiles 3
rem region_finder tiles 2
rem region_finder tiles 1

rem region_finder tiles e:/pacman/paper
rem on_finder tiles 18
region_finder tiles 17
region_finder tiles 16
region_finder tiles 15
region_finder tiles 14
region_finder tiles 13
region_finder tiles 12
region_finder tiles 11
region_finder tiles 10
region_finder tiles 9
region_finder tiles 8
region_finder tiles 7
region_finder tiles 6
region_finder tiles 5
region_finder tiles 4
region_finder tiles 3
region_finder tiles 2
region_finder tiles 1


PAUSE
